# Generated by Django 4.2.5 on 2023-10-12 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificacion',
            name='rfid',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='verificacion',
            name='telefono',
            field=models.CharField(max_length=10),
        ),
    ]
