# Generated by Django 4.2.5 on 2023-10-31 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_alter_verificacion_rfid_alter_verificacion_telefono'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroAcceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('verificacion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='login.verificacion')),
            ],
        ),
    ]
