# Generated by Django 4.2.5 on 2023-11-24 06:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_registroacceso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificacion',
            name='contrasena',
            field=models.CharField(max_length=6, unique=True, validators=[django.core.validators.MinLengthValidator(6)]),
        ),
    ]
